version: "3.1"

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456789
      POSTGRES_DB: taskflow
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - app-network
    restart: unless-stopped

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - app-network
    restart: unless-stopped

  taskflow:
    container_name: taskflow
    build: .
    depends_on:
      - postgres
      - redis
    ports:
      - "8080:8080"
    networks:
      - app-network
    restart: unless-stopped
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/taskflow?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456789
      SPRING_REDIS_HOST: redis
      SPRING_EMAIL_PASSWORD:
      SPRING_EMAIL:

networks:
  app-network:
    driver: bridge

volumes:
  postgres:
