spring:
  application:
    name: taskflow
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/taskflow?createDatabaseIfNotExist=true}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:123456789}
  jackson:
    property-naming-strategy: SNAKE_CASE
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: 6379
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SPRING_EMAIL}
    password: ${SPRING_EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: "*"

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui-custom.html

app:
  openapi:
    dev-url: http://localhost:8080

logging:
  level:
    org:
      springframework:
        security: DEBUG
        web:
          client:
            RestTemplate: DEBUG